[2025-04-04T10:00:04.725+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_reddit_posts.fetch_reddit scheduled__2025-04-04T09:57:04.185729+00:00 [queued]>
[2025-04-04T10:00:04.731+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_reddit_posts.fetch_reddit scheduled__2025-04-04T09:57:04.185729+00:00 [queued]>
[2025-04-04T10:00:04.732+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-04T10:00:04.743+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_reddit> on 2025-04-04 09:57:04.185729+00:00
[2025-04-04T10:00:04.747+0000] {standard_task_runner.py:57} INFO - Started process 885 to run task
[2025-04-04T10:00:04.750+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_reddit_posts', 'fetch_reddit', 'scheduled__2025-04-04T09:57:04.185729+00:00', '--job-id', '1237', '--raw', '--subdir', 'DAGS_FOLDER/fetch_reddit.py', '--cfg-path', '/tmp/tmpcj5yisgx']
[2025-04-04T10:00:04.753+0000] {standard_task_runner.py:85} INFO - Job 1237: Subtask fetch_reddit
[2025-04-04T10:00:04.793+0000] {task_command.py:415} INFO - Running <TaskInstance: fetch_reddit_posts.fetch_reddit scheduled__2025-04-04T09:57:04.185729+00:00 [running]> on host 0e1756f5e2b4
[2025-04-04T10:00:04.857+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_reddit_posts' AIRFLOW_CTX_TASK_ID='fetch_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T09:57:04.185729+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T09:57:04.185729+00:00'
[2025-04-04T10:00:04.864+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_reddit.py", line 31, in fetch_reddit_posts
    for submission in reddit.subreddit("datascience").new(limit=200):
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/listing/generator.py", line 66, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/listing/generator.py", line 90, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/reddit.py", line 731, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/reddit.py", line 514, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/reddit.py", line 963, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/auth.py", line 473, in refresh
    self._request_token(
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/auth.py", line 51, in _post
    response = self._requestor.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/prawcore/requestor.py", line 70, in request
    raise RequestException(exc, args, kwargs) from None
prawcore.exceptions.RequestException: error with request Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' PRAW/7.8.1 prawcore/2.4.0'
[2025-04-04T10:00:04.874+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_reddit_posts, task_id=fetch_reddit, execution_date=20250404T095704, start_date=20250404T100004, end_date=20250404T100004
[2025-04-04T10:00:04.883+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1237 for task fetch_reddit (error with request Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' PRAW/7.8.1 prawcore/2.4.0'; 885)
[2025-04-04T10:00:04.922+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-04T10:00:04.934+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
